export default {
    FAIL: 'success',
    NO_EMAIL_PASSWORD: 'Error: Email or Password cannot be blank.',
    SIGNED_UP: 'Signed up successfully',
    SIGN_UP_KEYS: [
        'address',
        'city',
        'country',
        'createdAt',
        'email',
        'firstName',
        'lastName',
        'password',
        'phoneNumber',
        'state',
        'updatedAt',
        'username',
    ],
    SUCCESS: 'success',
    USER_EXIST: 'Error: Account already exist.',
};
